### ISSUE TITLE
Not loading in Safari on a Mac

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-facebook#23]
Works on Chrome and Firefox desktop but on Safari Version 10.1 (11603.1.30.0.34) on 10.11.6 it doesn't seem to load the Facebook API. 

No errors just not loading.

**Comment by robertocarroll** [comment]
- http://stackoverflow.com/questions/42154874/fb-ui-not-working-on-safari
- "try cookie false when initializing Facebook sdk" http://stackoverflow.com/questions/23372290/facebook-fb-ui-dialog-no-popup-on-safari?rq=1

**Comment by robertocarroll** [comment]
The button loads on mobile Safari.

**Comment by pauldwaite** [comment]
I can’t currently reproduce this problem — it works fine for me in Safari.

Admittedly, I’m on a different minor version of 10.1 (12603.1.30.0.34), and on macOS 10.12.4, but I’d be surprised if that caused a difference.

A comment on that second Stack Overflow link suggested it might be caused by Safari’s pop-up blocking option (Safari > Preferences > Security > Web content: Block pop-up windows). If you can still reproduce the issue, it might be worth seeing if that setting is enabled, and if so, whether disabling it removes the issue. I’ve tried running the site locally in a private browsing window with that setting turned on, and it still works.

**Comment by robertocarroll** [comment]
Thanks for reviewing this bug. It's still not working for me in Safari. It doesn't even load the API so the button never appears. If it works for you, I'm going to close the issue because my Safari has gone a bit odd of late. Please re-open if it doesn't work for you in Safari (as you say, if the entire Facebook API is broken on Safari, there would be lots of people complaining).
